README.md

Currently in the README file, the command for create a sandbox is wrong.

Wrong sub command name for stack

---

components/gateway/.goreleaser.yml

builder-config.json was removed since we are not building it from a config file anymore

fix: remove missing extra files for go releaser

---

.gitignore
components/gateway/pkg/plugins/versions.go

This PR fix the fact that the health field in the /versions json response was omitted if set to false.
Before:
```
{
"name": "payments",
"version": "develop"
},
```
After:
```
{
"name": "payments",
"version": "develop",
"health": false
},
```
Tested using local env.

fix: always send health field in /versions json response

---

components/ledger/cmd/container_test.go
components/ledger/cmd/main_test.go
components/ledger/cmd/root_test.go
components/ledger/cmd/script_check.go
components/ledger/cmd/script_exec.go
components/ledger/cmd/script_test.go
components/ledger/cmd/storage_test.go
components/ledger/go.mod
components/ledger/go.sum

The recently added tests inside cmd/ was not starting a dedicated pg server instance, breaking a simple "go test" which was working on all other tests.
Also, changes really check errors of the commands.
And changes fix viper missing flags (was working only because tests inside root_test.go was configuring global env var).

fix: tests with postgres server

---

components/gateway/pkg/plugins/versions.go

Versions should always be "unknown" if not found or empty

fix: versions field in gateway should be consistent

---

components/auth/.goreleaser.yml
components/fctl/.goreleaser.yml
components/operator/.goreleaser.yml
components/orchestration/.goreleaser.yml
components/payments/.goreleaser.yml
components/search/.goreleaser.yml
components/wallets/.goreleaser.yml
components/webhooks/.goreleaser.yml

Component versions are set to "develop" on all components instead of the current versions/tag.
In order to set package variable using ldflags, we have to use the importpath from the go.mod file in every components, which was wrong for all components, hence the version set to the default version "develop"

fix: fix ldflags for Version with goreleaser

---

components/gateway/Caddyfile
components/gateway/pkg/plugins/versions.go
components/operator/internal/controllers/stack/stack_reconciler.go
components/operator/internal/controllers/stack/suite_test.go
components/operator/internal/controllers/stack/testdata/resources/configmaps--v1/gateway-config.yaml
components/operator/internal/handlers/handler_gateway.go
components/operator/internal/modules/service.go
components/operator/main.go
config/gateway/Caddyfile

```
{
"region": "eu-west-1",
"env": "sandbox" // or "production" or "staging" or ? idk !
"versions": [
{
"name": "wallets",
"version": "develop",
"health": true
},
...
```
We want to expose the environment the stack is running on: staging, sandbox, etc...
By passing a flag to the operator down to the gateway using the caddy file for the versions endpoint
Tested using local env.

feat: add environment to versions endpoint

---

components/ledger/pkg/storage/sqlstorage/worker/worker.go

Even if we have an error, the clients will retry, so release the models array

fix: if we have an error, still release all models

---

components/ledger/pkg/ledger/ledger.go
components/ledger/pkg/storage/sqlstorage/errors/errors.go
components/ledger/pkg/storage/sqlstorage/ledger/logs.go
components/ledger/pkg/storage/sqlstorage/module.go
libs/go-libs/go.mod
libs/go-libs/pgtesting/postgres.go

Bulk insert were done thanks to bun and mulitple
values for the insert postgres method. In order to improve the performances, let's move to copy for
these bulk inserts.
Also, using copy wiuth bun is not working if the pgx driver is used when creating the bun db.

feat: move bulk insert to copy with bun

---

components/ledger/cmd/container_test.go
components/ledger/pkg/api/controllers/account_controller.go
components/ledger/pkg/api/controllers/transaction_controller.go
components/ledger/pkg/ledger/benchmarks_test.go
components/ledger/pkg/ledger/execute_script.go
components/ledger/pkg/ledger/execute_script_test.go
components/ledger/pkg/ledger/ledger.go
components/ledger/pkg/ledger/ledger_test.go
components/ledger/pkg/ledger/logs.go

We want to make only one logs insertion in order to fail all when the query fails.

feat: combine logs before insertion

---

components/ledger/pkg/api/controllers/swagger.yaml

This PR adds an example on how to use the metadata filter for the GET /transactions route.
For whatever reason our swagger has decided not to display it in the example area so here we are

chore: add example in the description for metadata filter

---

components/ledger/pkg/analytics/segment.go
components/ledger/pkg/ledger/ledger.go
components/ledger/pkg/ledger/query/worker.go
components/ledger/pkg/ledger/query/worker_test.go
components/ledger/pkg/ledger/runner/runner.go
components/ledger/pkg/storage/driver.go
components/ledger/pkg/storage/errors.go
components/ledger/pkg/storage/sqlstorage/driver_test.go
components/ledger/pkg/storage/sqlstorage/errors/errors.go
components/ledger/pkg/storage/sqlstorage/ledger/accounts.go
components/ledger/pkg/storage/sqlstorage/ledger/balances.go
components/ledger/pkg/storage/sqlstorage/ledger/logs.go
components/ledger/pkg/storage/sqlstorage/ledger/migration.go
components/ledger/pkg/storage/sqlstorage/ledger/store.go
components/ledger/pkg/storage/sqlstorage/ledger/store_test.go
components/ledger/pkg/storage/sqlstorage/ledger/transactions.go
components/ledger/pkg/storage/sqlstorage/ledger/volumes.go
components/ledger/pkg/storage/sqlstorage/system/configuration.go

The storage should not take a decision when the data is not found.
We have to let the caller decide what he wants to do when the data is not found.

feat: rework storage errors

---

components/ledger/pkg/ledger/query/worker.go
components/ledger/pkg/ledger/query/worker_test.go
components/ledger/pkg/ledger/resolver.go

- Remove the `driver` field from the `Worker` struct
- Change the `initLedgers` method to `initLedger` and remove the loop

fix: refactor query Worker struct and methods

---

components/ledger/pkg/storage/sqlstorage/driver.go
components/ledger/pkg/storage/sqlstorage/ledger/logs.go
components/ledger/pkg/storage/sqlstorage/ledger/store.go

When calling the RunInTransaction store function, a sub store is created everytime. When creating a new store, a logs worker is created also using context.Background, and the stop function was never called. This commit fixes that by simply adding the logs worker closing inside the ledger close and calling the close when we finish the transaction

fix: fix memory leak with store logs worker not closed

---

components/ledger/pkg/core/value.go
components/ledger/pkg/machine/script/compiler/compiler.go
components/ledger/pkg/machine/script/compiler/compiler_test.go
components/ledger/pkg/machine/script/compiler/source.go
components/ledger/pkg/machine/vm/machine.go
components/ledger/pkg/machine/vm/machine_test.go
components/ledger/pkg/machine/vm/program/instructions.go

Be able to send monetary with arithmetic computation such as:
```
vars {
asset $asset
monetary $mon1 = balance($account_a, $asset)
monetary $mon2 = balance($account_b, $asset)
}
send $mon1 + $mon2 - [$asset 1] (
source = @wallet
destination = @account_c
)
```

feat: Numscript: Send monetary with arithmetic

---

components/ledger/libs/logging/logrus.go
components/ledger/libs/otlp/cli.go
components/ledger/libs/otlp/otlpmetrics/module.go
components/ledger/libs/otlp/otlptraces/traces.go
components/stargate/cmd/root.go
libs/go-libs/otlp/cli.go
libs/go-libs/otlp/otlpmetrics/module.go
libs/go-libs/otlp/otlptraces/traces.go

When setting the metrics and traces flags at true
resources were created twice within fx, hence the
crash. This PR fixes it

fix: crash with resources loaded twice

---

components/stargate/internal/client/client.go

instead of panicking, let's return an error in the stream

feat: send an error when failing to connect to gateway

---

components/fctl/cmd/ledger/accounts/list.go
components/fctl/cmd/ledger/accounts/set_metadata.go
components/fctl/cmd/ledger/accounts/show.go
components/fctl/cmd/ledger/balances.go
components/fctl/cmd/ledger/list.go
components/fctl/cmd/ledger/send.go
components/fctl/cmd/ledger/serverinfo.go
components/fctl/cmd/ledger/stats.go
components/fctl/cmd/ledger/transactions/list.go
components/fctl/cmd/ledger/transactions/num.go
components/fctl/cmd/ledger/transactions/revert.go
components/fctl/cmd/ledger/transactions/root.go
components/fctl/cmd/ledger/transactions/set_metadata.go
components/fctl/cmd/ledger/transactions/show.go

Response has `Data` object intermediary but sdk doesn't :
- fctl ledger send
- fctl ledger list
- fctl ledger server-infos
Metadata map[string][string] and response from sdk is map[string][[]string{}]:
- fctl ledger transaction revert

feat: fctl-tojson-ledger

---

components/fctl/cmd/ledger/internal/show.go
components/fctl/cmd/ledger/transactions/show.go

client in 'field := reflect.ValueOf(client).Elem().FieldByName('_securityClient')' seems to want an adress

fix: fctl stack show

---

components/ledger/openapi.yaml

- Update descriptions of metadata filters in swagger.yaml file

docs: update metadata filter descriptions in swagger.yaml file

---

components/fctl/.goreleaser.yml
components/fctl/Dockerfile
components/fctl/cmd/login/login.go
components/fctl/cmd/prompt.go
components/fctl/cmd/root.go
components/fctl/cmd/stack/controller.go
components/fctl/cmd/stack/create.go
components/fctl/cmd/stack/delete.go
components/fctl/cmd/stack/internal/global.go
components/fctl/cmd/stack/list.go
components/fctl/cmd/stack/restore.go
components/fctl/cmd/stack/root.go
components/fctl/cmd/stack/show.go
components/fctl/cmd/webhooks/secret.go
components/fctl/pkg/approval.go
components/fctl/pkg/clients.go
components/fctl/pkg/command.go
components/fctl/pkg/config.go
components/fctl/pkg/controller.go
components/fctl/pkg/file.go
components/fctl/pkg/flags.go
components/fctl/pkg/global.go
components/fctl/pkg/http.go
components/fctl/pkg/manager.go
components/fctl/pkg/profile.go

+ Add GetFlags Command to return a FLagSet
- Remove Cobra args from Run & Render
Convert command that was accepting *cobra.Command only to retrieve cmd.Flags() that is implementing *flag.FlagSet
type StackCreateControllerConfig struct {
context     context.Context
use         string
description string
aliases     []string
out         io.Writer
flags       *flag.FlagSet
args        []string
}

feat(fctl): remove-cobra-controller-dep

---

components/payments/internal/app/connectors/bankingcircle/client/auth.go
components/payments/internal/app/connectors/bankingcircle/client/client.go

login is done at every call if the token is not valid anymore, no need to do it when creating the connector

fix(payments): banking circle login

---

components/operator/garden/example-v1beta3.yaml

According to 
```
apiVersion: stack.formance.com/v1beta3
kind: Versions
```
```
Stargate string `json:"stargate"`
```
wrong key mention in `example-v1beta3.yaml`

fix: example crds mention a wrong key

---

.moon/tasks/go-application.yml
components/fctl/cmd/orchestration/instances/describe.go

We don't need the mod deps for release as it will run everything that have been previously ran by others workflow

fix: remove mod deps for release

---

components/operator/Makefile
components/operator/README.md
components/operator/commands.garden.yaml
components/operator/garden.yml
components/operator/garden/cert-manager/garden.yaml
components/operator/garden/dex/garden.yaml
components/operator/garden/elasticsearch/garden.yaml
components/operator/garden/jaeger/garden.yaml
components/operator/garden/k3d.yaml
components/operator/garden/minio/garden.yaml
components/operator/garden/nats/garden.yaml
components/operator/garden/otel-collector/garden.yaml
components/operator/garden/postgres/garden.yaml
components/operator/garden/reloader/garden.yaml
components/operator/garden/traefik/garden.yaml
components/operator/project.garden.yaml

- Bump garden project version to garden.io/v1
- It allow us to trigger action https://docs.garden.io/reference/action-types
- `kind: Module` is deprecated
- Convert every `kind: Module` to `kind: Deploy`
- Install default registry as k3d-registry.host.k3d.internal on static port 12345
- Update makefile:
- docker-push
- docker-build
- helm-local-install
- helm-local-upgrade

feat: upgrade garden project

---

docs/docs/ledger/reference/numscript/postings.mdx
docs/sidebars.js

In addition to explaining the basic posting syntax, this page explains the `send [ASSET *] ( [...] )` syntax.

docs: Add a reference page about postings

---

docs/docs/getting-started/invite.mdx
docs/sidebars.js

- Add a new file `invite.mdx` in the `docs/docs/getting-started` directory
- Add content for inviting users to use the Formance stack in the `invite.mdx` file
- Provide instructions for inviting users using the `fctl` command line tool
- Provide instructions for inviting users using the web interface
- Update the `sidebars.js` file to include a link to the `invite` documentation page in the sidebar

docs: add documentation for user invitation process

---

components/operator/internal/controllers/stack/testdata/monopod-disabled-one-service/results/deployments-apps-v1/monopod-disabled-one-service.yaml
components/operator/internal/controllers/stack/testdata/monopod-latest/results/deployments-apps-v1/monopod-latest.yaml
components/operator/internal/controllers/stack/testdata/monopod-ledgerv1/results/deployments-apps-v1/monopod-ledgerv1.yaml
components/operator/internal/controllers/stack/testdata/monopod-search-before-v0.7.0/results/deployments-apps-v1/monopod-search-before-v0-7-0.yaml
components/operator/internal/controllers/stack/testdata/multipod-debug/results/deployments-apps-v1/search-benthos.yaml
components/operator/internal/controllers/stack/testdata/multipod-disabled-one-service/results/deployments-apps-v1/search-benthos.yaml
components/operator/internal/controllers/stack/testdata/multipod-latest-no-monitoring/results/deployments-apps-v1/search-benthos.yaml
components/operator/internal/controllers/stack/testdata/multipod-latest/results/deployments-apps-v1/search-benthos.yaml
components/operator/internal/controllers/stack/testdata/multipod-service-annotation/results/deployments-apps-v1/search-benthos.yaml
components/operator/internal/modules/pod.go

When updating deployments, do not change the previous number of replicas

feat(operator): ignore replicas changed

---

components/operator/apis/stack/v1beta3/ledger_types.go
components/operator/config/crd/bases/stack.formance.com_configurations.yaml
components/operator/internal/modules/ledger/handler.go
components/operator/internal/modules/pod.go
components/operator/internal/modules/service.go

Add deployment strategy for the ledger on the operator.
The operator now deploy two Deployments for the ledger : 
* A writer : Numbers of replicas to 1
* Readers: Number of replicas initially set to 1 but can be changed
Also, the gateway will route all http requests with GET, OPTIONS or HEAD methods to the readers, others to the writer.

feat: add deployment strategy on ledger

---

components/operator/internal/modules/module.go

When scaling down a migration, if pod is not yet scaled down, the migration is still run because we're returning nil. This PR ensures that the reconciliation fails and start again until the pod is effectivement scaled down
Fixes ENG-231

fix(operator): fix pre-run migrations

---

components/payments/docker-compose.yml
components/payments/local_env/postgres/init.sql

The docker compose in the components/payments/ was not working anymore after the splitting of payments in two services. This PR fixes that.
It also adds the possibility to use the `POSTGRES_PORT` env var to configure the postgres port.
Fixes ENG-249

fix(payments): fix docker compose to test it locally

---

components/ledger/internal/storage/ledgerstore/migrations/0-init-schema.sql
components/ledger/internal/storage/ledgerstore/transactions.go
components/ledger/internal/storage/ledgerstore/transactions_test.go
components/ledger/internal/storage/ledgerstore/utils.go

Benchmarks results (run 2 times) : 
`
1.
+benchstat | LogsInsertion-8                                                             3.820m ± 5%   3.577m ± 3%   -6.37% (p=0.000 n=10)
+benchstat | LogsInsertionReusingAccount-8                                               3.369m ± 7%   3.585m ± 5%   +6.42% (p=0.011 n=10)
+benchstat | List/listing_transactions_with_no_query-8                                   980.7µ ± 1%   555.1µ ± 1%  -43.40% (p=0.000 n=10)
+benchstat | List/listing_transactions_using_an_exact_address-8                          902.0µ ± 1%   782.5µ ± 1%  -13.24% (p=0.000 n=10)
+benchstat | List/listing_transactions_using_an_address_segment-8                       1030.6µ ± 1%   964.7µ ± 1%   -6.39% (p=0.000 n=10)
+benchstat | 
+benchstat | …

feat(ledger): add some columns on transactions table to speed up read queries

---

components/payments/cmd/connectors/internal/connectors/atlar/time.go

Parsing the `Account.Timestamp` has uncovered a bug in timestamp parsing, as this is the only timestamp not bing in UTC time. It has a timezone attached to it. I discovered, that go offers the handy `time.RFC3339Nano` as a ready made format string for parsing these dates and times.  I used that instead, that fixes the task crashing.

fix: Fix time parsing in Atlar connector

---

components/payments/cmd/connectors/internal/connectors/atlar/task_fetch_payments.go

I talked to the guys over at Atlar about what their transaction statuses mean (the documentation is hard to find). After some clarifications, here are some fixes to `determinePaymentStatus()`.

fix(payments): Correctly determine status of payment in Atlar connector

---

components/payments/cmd/connectors/internal/connectors/atlar/task_fetch_accounts.go
components/payments/cmd/connectors/internal/connectors/atlar/task_fetch_payments_test.go
components/payments/cmd/connectors/internal/connectors/atlar/task_fetch_transactions.go
components/payments/cmd/connectors/internal/connectors/atlar/task_main.go

Here is a list of things this PR fixes
- Ingest the absolute value of an Atlar Transfer into Formance Payments
- Implement timeouts on all atlar client requests

fix(payments): Various fixes for the Atlar connector

---

components/payments/cmd/connectors/internal/connectors/atlar/account_utils.go

As metadata is currently saved, we took a lot of care to save the information as lossless as possible.
However, when one does not know the market an account operates in, it's currently hard to get the IBAN. We'll need the IBAN in flows, so this PR offers a quick fix to the issue. Once we have some room to breathe, we might have to look back into how to solve this in a clean manner.

fix(payments): Make IBAN easier to get() in account metadata (ATLAR)

---

components/payments/cmd/connectors/internal/connectors/atlar/task_fetch_transactions.go

This PR fixes an issue with payment statuses I discovered today while testing incoming transactions.
Here's some context:

fix(payments): A payment has succeeded when booked

---

components/fctl/cmd/cloud/organizations/users/root.go
components/fctl/cmd/stack/roles/root.go
components/fctl/pkg/clients.go
components/fctl/pkg/command.go

- fctl cloud organization users
- fctl stack roles
- fctl cloud organization create/update
- fctl auth create/update
=> Are not impacted and additional parameters are ignored by auth & membership api

feat: check membership version

---

components/payments/cmd/connectors/internal/connectors/atlar/task_payments.go

SEPA allows for empty remittance info. We don't need to nor should we reject payments with an empty description.

feat(payments): Remove requirement for non-empty payment description

---

components/ledger/internal/machine/script/compiler/source.go
components/ledger/internal/machine/vm/machine_test.go

https://github.com/formancehq/ledger/pull/474

fix(ledger): Overdraft with Max

---

components/payments/go.mod
components/payments/go.sum
tests/integration/go.mod
tests/integration/go.sum

The updated version of the client provides the error response body when posting a credit transfer initiation.
While Atlar is adding some more documentation on errors at https://cdn.atlar.com/api/swagger.json this update will allow us to better debug payment initiation failures.

fix(payments): Upgrade Atlar client to v1.2.1

---

components/payments/cmd/connectors/internal/connectors/atlar/task_payments.go
components/payments/internal/models/transfer_initiation.go

When creating an Atlar payment, we want to serialize the external ID with the number of retries of the transfer, and not the length of the adjustements which changes if the payments is created on Atlar side, hence the error that the payment was not found when searching to update the status.

fix(payments): fix atlar external ID when creating a payment

---

components/payments/cmd/connectors/internal/connectors/atlar/task_fetch_transactions.go

This PR fixes a typo in the transaction metadata.
Since we have not gone live, yet, a migration is not necessary.

fix(payments): Typo in counterparty name metadata when fetching transactions

---

components/payments/cmd/connectors/internal/connectors/stripe/translate.go

For payments transactions t ype, we don't need to
fill the scheme as it will always be other.

fix(payments): fix error when missing scheme

---

components/ledger/libs/bun/bunconnect/flags.go
components/ledger/libs/bun/bunmigrate/command.go
components/ledger/libs/bun/bunmigrate/run.go
components/ledger/libs/bun/bunmigrate/run_test.go
components/operator/docs/crd.md
components/operator/helm/templates/gen/apiextensions.k8s.io_v1_customresourcedefinition_auths.formance.com.yaml
components/operator/helm/templates/gen/apiextensions.k8s.io_v1_customresourcedefinition_gateways.formance.com.yaml
components/operator/helm/templates/gen/apiextensions.k8s.io_v1_customresourcedefinition_ledgers.formance.com.yaml
components/operator/helm/templates/gen/apiextensions.k8s.io_v1_customresourcedefinition_orchestrations.formance.com.yaml
components/operator/helm/templates/gen/apiextensions.k8s.io_v1_customresourcedefinition_payments.formance.com.yaml
components/operator/helm/templates/gen/apiextensions.k8s.io_v1_customresourcedefinition_reconciliations.formance.com.yaml
components/operator/helm/templates/gen/apiextensions.k8s.io_v1_customresourcedefinition_searches.formance.com.yaml
components/operator/helm/templates/gen/apiextensions.k8s.io_v1_customresourcedefinition_stargates.formance.com.yaml
components/operator/helm/templates/gen/apiextensions.k8s.io_v1_customresourcedefinition_wallets.formance.com.yaml
components/operator/helm/templates/gen/apiextensions.k8s.io_v1_customresourcedefinition_webhooks.formance.com.yaml
libs/go-libs/bun/bunconnect/flags.go
libs/go-libs/bun/bunmigrate/command.go
libs/go-libs/bun/bunmigrate/run.go
libs/go-libs/bun/bunmigrate/run_test.go

feat(*): create databases in migrator

---

components/ledger/openapi/v1.yaml

Turns out the maximum page size is 1000
Also, the `/balances` endpoint accepts `pageSize`

fix: update ledger v1 docs about pageSize

---

components/fctl/cmd/stack/controller.go
components/fctl/cmd/stack/create.go
components/fctl/cmd/stack/restore.go
components/fctl/cmd/stack/upgrade.go

Remplacement du polling sur auth (l'openid config) vers un polling du status via membership

feat: status can now be handle by membership on create, restore, upgrade

---

components/operator/api/formance.com/v1beta1/shared.go
components/operator/helm/templates/gen/apiextensions.k8s.io_v1_customresourcedefinition_stacks.formance.com.yaml

Benthos es output does not build requests properly when the url terminates with a '?'. 
'http://elasticsearch:9200?' will fail for example, whereas 'http://elasticsearch:9200?foo=bar' will be ok.

fix(operator): benthos deployment

---

.github/workflows/main.yml

When secrets change (as for GITHUB_TOKEN), the WITH DOCKER instructions are not cached.
I think it is related to https://github.com/earthly/earthly/issues/3298.
Since we don't need these vars, just drop it from the pipeline.

fix(ci): cache invalidation

---

components/payments/cmd/connectors/internal/connectors/atlar/task_fetch_accounts.go
components/payments/cmd/connectors/internal/connectors/bankingcircle/client/payments.go
components/payments/cmd/connectors/internal/connectors/bankingcircle/client/transfer_payouts.go
components/payments/cmd/connectors/internal/connectors/bankingcircle/task_fetch_accounts.go
components/payments/cmd/connectors/internal/connectors/bankingcircle/task_fetch_payments.go
components/payments/cmd/connectors/internal/connectors/bankingcircle/task_payments.go
components/payments/cmd/connectors/internal/connectors/currency/amount.go
components/payments/cmd/connectors/internal/connectors/currency/amount_test.go
components/payments/cmd/connectors/internal/connectors/currencycloud/client/balances.go
components/payments/cmd/connectors/internal/connectors/currencycloud/client/payout.go
components/payments/cmd/connectors/internal/connectors/currencycloud/client/transactions.go
components/payments/cmd/connectors/internal/connectors/currencycloud/client/transfer.go
components/payments/cmd/connectors/internal/connectors/currencycloud/task_fetch_balances.go
components/payments/cmd/connectors/internal/connectors/currencycloud/task_fetch_transactions.go
components/payments/cmd/connectors/internal/connectors/currencycloud/task_payments.go
components/payments/cmd/connectors/internal/connectors/modulr/client/payout.go
components/payments/cmd/connectors/internal/connectors/modulr/client/transfer.go
components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_accounts.go
components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_transactions.go
components/payments/cmd/connectors/internal/connectors/modulr/task_payments.go
components/payments/cmd/connectors/internal/connectors/moneycorp/client/payout.go
components/payments/cmd/connectors/internal/connectors/moneycorp/client/transfer.go
components/payments/cmd/connectors/internal/connectors/moneycorp/task_fetch_balances.go
components/payments/cmd/connectors/internal/connectors/moneycorp/task_fetch_transactions.go
components/payments/cmd/connectors/internal/connectors/moneycorp/task_payments.go
components/payments/cmd/connectors/internal/connectors/wise/client/quotes.go
components/payments/cmd/connectors/internal/connectors/wise/task_fetch_profiles.go
components/payments/cmd/connectors/internal/connectors/wise/task_fetch_transfers.go
components/payments/cmd/connectors/internal/connectors/wise/task_payments.go

feat(payments): handle precision from string

---

Earthfile
components/Earthfile
components/fctl/Earthfile
components/ledger/Earthfile
components/ledger/libs/Earthfile
components/operator/Earthfile
components/payments/Earthfile
ee/Earthfile
ee/agent/Earthfile
ee/auth/Earthfile
ee/gateway/Earthfile
ee/orchestration/Earthfile
ee/reconciliation/Earthfile
ee/search/Earthfile
ee/stargate/Earthfile
ee/wallets/Earthfile
ee/webhooks/Earthfile
helm/Earthfile
helm/regions/Earthfile
libs/go-libs/Earthfile
releases/Earthfile
tests/benchmarks/Earthfile
tests/integration/Earthfile
tools/operator-utils/Earthfile

feat: use main for earthly core

---

components/payments/cmd/connectors/internal/connectors/atlar/task_main.go
components/payments/cmd/connectors/internal/task/errors.go
components/payments/cmd/connectors/internal/task/scheduler.go
components/payments/cmd/connectors/internal/task/scheduler_test.go

The atlar main task if the one launching all other tasks every polling duration. if we have an error during scheduling we wanna retry, otherwise, all task will never be launched again.

feat(payments): retry atlar main task on scheduling error

---

components/operator/internal/resources/settings/helpers.go
components/operator/internal/resources/settings/helpers_test.go
components/operator/internal/tests/database_controller_test.go

- **feat(operator): refacto with split key**
- **feat(operator): handle segment composed with '.'**

feat(operator): segment setting can have . when surrounded by quotes

---

components/ledger/internal/api/v2/controllers_accounts_test.go
components/ledger/internal/api/v2/controllers_balances_test.go
components/ledger/internal/api/v2/controllers_transactions_test.go
components/ledger/internal/api/v2/controllers_volumes_test.go
components/ledger/internal/storage/ledgerstore/accounts.go
components/ledger/internal/storage/ledgerstore/accounts_test.go
components/ledger/internal/storage/ledgerstore/balances.go
components/ledger/internal/storage/ledgerstore/balances_test.go
components/ledger/internal/storage/ledgerstore/transactions.go
components/ledger/internal/storage/ledgerstore/transactions_test.go
components/ledger/internal/storage/ledgerstore/volumes.go
components/ledger/internal/storage/ledgerstore/volumes_test.go
libs/go-libs/query/expression.go

Add filter $exists: { metadata: XXX} to endpoints accounts, transactions, volumes and balances

feat(ledger): ENG-986 ability to filter on a metadata existence

---

components/payments/cmd/connectors/internal/connectors/atlar/client/transactions.go
components/payments/cmd/connectors/internal/connectors/atlar/task_fetch_transactions.go
components/payments/cmd/connectors/internal/connectors/atlar/task_payments.go
components/payments/docker-compose.yml

This PR adds a Payment ID to a transfer initiation only once once Atlar reports a transaction (Formance "Payment") connected to the transfer initiation.

fix(payments): wrong related payment ids

---

components/payments/cmd/connectors/internal/connectors/atlar/task_payments.go
components/payments/cmd/connectors/internal/connectors/dummypay/connector_test.go
components/payments/cmd/connectors/internal/ingestion/ingester.go
components/payments/cmd/connectors/internal/ingestion/transfer_initiation.go

In some cases, we only want to send one events when updating the status and adding a new related payments to a transfer initiation instead of two events like we have right now.
Fixes ENG-1161

feat(payments): only send one events when updating tf

---

components/ledger/internal/machine/vm/machine_test.go

low priority pr, a test was not actually running and this line enables it again

chore(ledger): add disabled test

---

ee/wallets/pkg/error.go
ee/wallets/pkg/ledger_interface.go
ee/wallets/pkg/manager.go

We spotted a difference between ledger v1 and ledger v2 when getting an account. In case of an account not found we still want to create the balance on wallet side
Fixes ENG-1251

fix(wallets): fix errors when creating balance

---

components/operator/internal/resources/ledgers/deployments.go
components/operator/internal/tests/ledger_controller_test.go

- **feat: add method lock/unlock on stack**
- **feat: delete deployment only on strategy update**

fix(operator): only delete ledger deployment on strategy change

---

docker-compose.yml

- payments api & connector services use the `/_live` endpoint (there is no `/_healthcheck`` endpoint).
- `wget` is not available in the `ledger:v2.0.3` image, so use `curl` like the other healthchecks.
- ledger service uses `/_healthcheck` endpoint for checking service health.

fix: docker compose healthchecks work again

---

components/payments/go.mod
components/payments/go.sum
components/payments/internal/connectors/engine/activities/storage_balances_delete.go
components/payments/internal/storage/accounts.go
components/payments/internal/storage/accounts_test.go
components/payments/internal/storage/balances.go
components/payments/internal/storage/balances_test.go
components/payments/internal/storage/bank_accounts.go
components/payments/internal/storage/bank_accounts_test.go
components/payments/internal/storage/connectors.go
components/payments/internal/storage/connectors_test.go
components/payments/internal/storage/main_test.go
components/payments/internal/storage/migrations/0-init-schema.sql
components/payments/internal/storage/payments.go
components/payments/internal/storage/payments_test.go
components/payments/internal/storage/pools.go
components/payments/internal/storage/pools_test.go
components/payments/internal/storage/schedules.go
components/payments/internal/storage/schedules_test.go
components/payments/internal/storage/states_test.go
components/payments/internal/storage/storage.go
components/payments/internal/storage/tasks_test.go
components/payments/internal/storage/utils_test.go
components/payments/internal/storage/webhooks.go
components/payments/internal/storage/webhooks_configs.go
components/payments/internal/storage/webhooks_configs_test.go
components/payments/internal/storage/webhooks_test.go
components/payments/internal/storage/workflow_instances.go
components/payments/internal/storage/workflow_instances_test.go

feat(payments): add storage tests and fix payments upsert

---

components/payments/cmd/api/internal/storage/payments.go
components/payments/cmd/api/internal/storage/payments_test.go
components/payments/cmd/connectors/internal/storage/connectors_test.go
components/payments/cmd/connectors/internal/storage/payments_test.go
components/payments/internal/storage/migrations_v1.x.go

We want to have an unique contraint on the reference of payments within the same connector, but not accross connectors

fix(payments): fix payment storage constraint

---

components/payments/cmd/connectors/internal/api/connector.go
components/payments/cmd/connectors/internal/connectors/duration.go

One of our customers has some problems when getting the config of the Atlar connector. After investigation, it was the custom duration struct that was failing to be marshalled before being sent to the client. A fix has been done a few weeks ago to fix the "pollingPeriod" custom duration in the configs, but Atlar has one more custom duration struct.
After investigation, it seems that the custom duration struct was not implementing correctly the Marshal interface, which was the cause of the wrong json sent through the api. Fixing this implementation allows us also to remove the api fix we've made.
Fixes PMNT-109

fix(api): fix polling duration wrongfully marshalled

---

components/payments/cmd/api/internal/api/backend/backend.go
components/payments/cmd/api/internal/api/backend/backend_generated.go
components/payments/cmd/api/internal/api/pools.go
components/payments/cmd/api/internal/api/pools_test.go
components/payments/cmd/api/internal/api/router.go
components/payments/cmd/api/internal/api/service/pools.go
components/payments/cmd/api/internal/api/service/pools_test.go
components/payments/cmd/api/internal/api/service/service.go
components/payments/cmd/api/internal/api/service/service_test.go
components/payments/cmd/api/internal/storage/balances.go
components/payments/cmd/api/internal/storage/balances_test.go

Fixes: PMNT-99
```
curl -D - \
-X GET \
http://localhost:8080/pools/3df2a762-7cd5-43e1-9f74-a8bb5cb860d5/balances/latest
HTTP/1.1 200 OK
Content-Type: application/json
Vary: Origin
Date: Wed, 09 Jul 2025 10:07:41 GMT
Content-Length: 42
{"data":[{"amount":945,"asset":"EUR/2"}]}
```
Account balances that make up the above:
```
[
{"cursor":{"pageSize":15,"hasMore":false,"data":[{"accountId":"eyJDb25uZWN0b3JJRCI6eyJQcm92aWRlciI6Ik1PTkVZQ09SUCIsIlJlZmVyZW5jZSI6IjBlM2Q1Y2MwLTk5NzMtNDVmOC04NmQ1LTA3ODU4ZWRhYzQ1YyJ9LCJSZWZlcmVuY2UiOiIzOTAzIn0","createdAt":"2025-07-09T10:01:27.149782Z","lastUpdatedAt":"2025-07-09T10:03:57.019456Z","currency":"EUR/2","asset":"EUR/2","balance":935}]}},
{"cursor":{"pageSize":15,"hasMore":false,"data":[{"accountId":"eyJDb25uZWN0b3JJRCI6eyJQcm92aWRlciI6Ik1PTkVZQ09SUCIsIl …
```

feat(pools): Backport new balances/latest endpoint to payments v2
