formancehq/stack

components/gateway/Caddyfile, components/gateway/pkg/plugins/versions.go, components/operator/internal/controllers/stack/stack_reconciler.go, components/operator/internal/controllers/stack/suite_test.go, components/operator/internal/controllers/stack/testdata/resources/configmaps--v1/gateway-config.yaml, components/operator/internal/handlers/handler_gateway.go, components/operator/internal/modules/service.go, components/operator/main.go, config/gateway/Caddyfile
This PR adds health check status and region information
Tested using local env.
This PR depends on https://github.com/formancehq/stack/pull/70
=> feat: gateway v2 add health and region in /versions response

components/ledger/cmd/container_test.go, components/ledger/go.mod, components/ledger/go.sum, components/ledger/pkg/api/controllers/account_controller.go, components/ledger/pkg/api/controllers/account_controller_test.go, components/ledger/pkg/api/controllers/ledger_controller_test.go, components/ledger/pkg/api/controllers/transaction_controller.go, components/ledger/pkg/core/log.go, components/ledger/pkg/core/log_test.go, components/ledger/pkg/core/numscript.go, components/ledger/pkg/ledger/benchmarks_test.go, components/ledger/pkg/ledger/execute_script.go, components/ledger/pkg/ledger/execute_script_test.go, components/ledger/pkg/ledger/ledger.go, components/ledger/pkg/ledger/ledger_test.go, components/ledger/pkg/ledger/storage.go, components/ledger/pkg/storage/sqlstorage/driver.go, components/ledger/pkg/storage/sqlstorage/ledger/accounts.go, components/ledger/pkg/storage/sqlstorage/ledger/commit.go, components/ledger/pkg/storage/sqlstorage/ledger/logs.go, components/ledger/pkg/storage/sqlstorage/ledger/store.go, components/ledger/pkg/storage/sqlstorage/ledger/store_test.go, components/ledger/pkg/storage/sqlstorage/ledger/transactions.go, components/ledger/pkg/storage/sqlstorage/worker/worker.go, components/ledger/pkg/storage/sqlstorage/worker/worker_test.go
BEWARE: batch size must stay at 1 until we have implemented the account based lock and CQRS for transactions, accounts and balances.
=> feat: introduce logs insertion by batch

docs/src/css/custom.css
=> style: :lipstick: Updated Graph looking on documentation

components/ledger/pkg/bus/message.go, components/search/benthos/streams/ledger_ingestion.yaml, components/search/benthos/streams/ledger_reindex_accounts.yaml, components/search/benthos/streams/ledger_reindex_transactions.yaml, components/search/benthos/streams/ledger_reindex_volumes.yaml
Remove this deprecated fields and modify benthos to use payload ledger field instead.
=> feat: remove deprecated ledger field for event message

docs/docs/ledger/get-started/installation.mdx
- Added instructions for creating a stack in the installation guide.
=> docs: add installation guide for creating a stack

components/ledger/pkg/api/controllers/account_controller_test.go, components/ledger/pkg/core/account.go, components/ledger/pkg/core/volumes.go, components/ledger/pkg/ledger/cache/cache.go, components/ledger/pkg/ledger/cache/cache_test.go, components/ledger/pkg/ledger/ledger_test.go, components/ledger/pkg/ledger/query/worker_test.go, components/ledger/pkg/ledger/runner/runner_test.go, components/ledger/pkg/machine/machine.go, components/ledger/pkg/storage/sqlstorage/ledger/accounts.go
Remove "Balances" field of structure "AccountAssetVolumes" as it is redundant with "Volumes" field.
=> feat: simplify model

components/ledger/Dockerfile, docker-compose.yml
- Update golang version from 1.19 to 1.20 in ledger Dockerfile
- Change ledger image from ghcr.io to formancehq in docker-compose.yml
- Add sslmode=disable to the STORAGE_POSTGRES_CONN_STRING environment variable in docker-compose.yml
- Change PUBLISHER_NATS_BROKER to PUBLISHER_NATS_URL in docker-compose.yml
=> chore: update dependencies and configurations for ledger service

components/ledger/pkg/api/controllers/swagger.yaml, openapi/build/generate.json, openapi/build/generate.json-e, sdks/go/api/openapi.yaml, sdks/go/api_accounts.go, sdks/go/docs/AccountsApi.md, sdks/java/api/openapi.yaml, sdks/java/docs/AccountsApi.md, sdks/java/src/main/java/com/formance/formance/api/AccountsApi.java, sdks/php/docs/Api/AccountsApi.md, sdks/php/lib/Api/AccountsApi.php, sdks/python/Formance/model/account_with_volumes_and_balances.py, sdks/python/Formance/model/account_with_volumes_and_balances.pyi, sdks/python/Formance/model/assets_balances.py, sdks/python/Formance/model/assets_balances.pyi, sdks/python/Formance/paths/api_ledger_ledger_accounts/get.py, sdks/python/Formance/paths/api_ledger_ledger_accounts/get.pyi, sdks/typescript-node/AccountsApi.md, sdks/typescript-node/apis/AccountsApi.ts, sdks/typescript-node/types/ObjectParamAPI.ts, sdks/typescript-node/types/ObservableAPI.ts, sdks/typescript-node/types/PromiseAPI.ts
Since we can have negative balances now with overdraft, let's remove this limitation on openapi side
=> fix: remove minimum balance for all balances operation

components/ledger/cmd/container.go, components/ledger/cmd/serve.go, libs/go-libs/ballast/ballast.go, libs/go-libs/ballast/module.go
cf: https://blog.twitch.tv/en/2019/04/10/go-memory-ballast-how-i-learnt-to-stop-worrying-and-love-the-heap/
Could be use by some of our biggest clients
=> feat: add ballast package

components/ledger/cmd/root.go, components/ledger/cmd/serve.go, libs/go-libs/service/app.go, libs/go-libs/service/logging.go
=> feat: use logger with json formatter

components/ledger/openapi.yaml, components/ledger/pkg/api/controllers/transaction_controller.go, components/ledger/pkg/api/controllers/transaction_controller_test.go, openapi/build/generate.json, openapi/build/generate.json-e, sdks/go/api/openapi.yaml, sdks/java/api/openapi.yaml, sdks/java/docs/TransactionsApi.md, sdks/php/lib/Api/TransactionsApi.php, sdks/python/Formance/paths/api_ledger_ledger_transactions_txid_revert/post.py, sdks/python/Formance/paths/api_ledger_ledger_transactions_txid_revert/post.pyi, sdks/python/docs/apis/tags/TransactionsApi.md, sdks/python/test/test_paths/test_api_ledger_ledger_transactions_txid_revert/test_post.py, sdks/typescript-node/TransactionsApi.md, sdks/typescript-node/apis/TransactionsApi.ts
- feat: disallow empty accounts
- feat: change status code from 200 to 201 on revert transactions
=> feat: change status code from 200 to 201 on revert transactions

components/ledger/cmd/root.go, components/ledger/go.mod, components/ledger/pkg/core/log.go, components/ledger/pkg/storage/sqlstorage/ledger/main_test.go, components/ledger/pkg/storage/sqlstorage/ledger/migrates/0-init-schema/any.go, components/ledger/pkg/storage/sqlstorage/ledger/migrates/0-init-schema/postgres.sql, components/ledger/pkg/storage/sqlstorage/migrations/migrations.go, components/ledger/pkg/storage/sqlstorage/migrations/migrations_test.go
=> feat: add migrations from v1.9.x to v2.x

components/payments/README.md
Don't know if you're still using notion. Feel free to edit my commit.
=> chore: OSS Roadmap numary -> formance

components/operator/internal/controllers/stack/testdata/monopod/configmaps--v1/gateway-config.yaml, components/operator/internal/controllers/stack/testdata/monopod/deployments-apps-v1/orga2-stack2.yaml, components/operator/internal/controllers/stack/testdata/monopod/services--v1/stargate.yaml, components/operator/internal/controllers/stack/testdata/monopod/services--v1/webhooks.yaml, components/operator/internal/controllers/stack/testdata/multipod/configmaps--v1/gateway-config.yaml, components/operator/internal/controllers/stack/testdata/multipod/deployments-apps-v1/stargate.yaml, components/operator/internal/controllers/stack/testdata/multipod/services--v1/stargate.yaml, components/operator/internal/handlers/handler_stargate.go, components/stargate/cmd/client.go, components/stargate/cmd/root.go, components/stargate/internal/client/controllers/info_controller.go, components/stargate/internal/client/module.go, components/stargate/internal/client/routes/routes.go
This PR adds healthcheck and info routes for stargate client
Fixes NUM-1711
=> feat: add router for stargate client

components/stargate/internal/server/grpc/api.go, components/stargate/internal/server/grpc/api_test.go, components/stargate/internal/server/http/controllers/stargate_controller.go, components/stargate/internal/server/http/controllers/stargate_controller_test.go, components/stargate/internal/utils/utils.go
=> feat: stargate fetch orga and stack ids in url path

components/stargate/internal/server/grpc/api.go, components/stargate/internal/server/http/controllers/controller.go, components/stargate/internal/server/http/controllers/errors.go, components/stargate/internal/server/http/controllers/stargate_controller.go, components/stargate/internal/server/http/controllers/stargate_controller_test.go
- Return 524 in case of nats error
- More precise logs
=> feat: last fixes for stargate server

components/orchestration/cmd/serve.go, components/orchestration/internal/api/handler_info.go, components/orchestration/internal/api/main_test.go, components/orchestration/internal/api/router.go, components/webhooks/cmd/serve.go, components/webhooks/pkg/server/handler.go, components/webhooks/pkg/server/info.go
=> feat: add missing info path for some services

components/fctl/cmd/wallets/balances/create.go, components/fctl/cmd/wallets/balances/list.go, components/fctl/cmd/wallets/balances/show.go, components/fctl/cmd/wallets/create.go, components/fctl/cmd/wallets/credit.go, components/fctl/cmd/wallets/debit.go, components/fctl/cmd/wallets/holds/confirm.go, components/fctl/cmd/wallets/holds/list.go, components/fctl/cmd/wallets/holds/show.go, components/fctl/cmd/wallets/holds/void.go, components/fctl/cmd/wallets/internal/print.go, components/fctl/cmd/wallets/internal/views/balance.go, components/fctl/cmd/wallets/internal/views/hold.go, components/fctl/cmd/wallets/internal/views/wallet.go, components/fctl/cmd/wallets/list.go, components/fctl/cmd/wallets/show.go, components/fctl/cmd/wallets/transactions/list.go, components/fctl/cmd/wallets/update.go
- Not tested `fctl wallets holds <confirm|list|show|void>`
=> feat: fctl-tojson-wallets

components/payments/internal/app/storage/payments.go
=> fix: payment upsert than was not an upsert

docs/docs/wallets/funds/adding-funds.mdx, docs/docs/wallets/funds/spending-funds.mdx
- Change the value of `type` from `account` to `ACCOUNT` in `adding-funds.mdx`
- Change the value of `type` from `account` to `ACCOUNT` in `spending-funds.mdx`
=> refactor: update `type` value in funds MDX files

openapi/build/generate.json, sdks/go/pkg/models/shared/paymentsaccount.go, sdks/java/lib/src/main/java/com/formance/formance_sdk/models/shared/PaymentsAccount.java, sdks/php/src/Models/Shared/PaymentsAccount.php, sdks/python/src/sdk/models/shared/paymentsaccount.py, sdks/typescript/src/sdk/models/shared/paymentsaccount.ts
=> fix(openapi): generation

components/fctl/cmd/ledger/list.go, components/fctl/go.mod, components/fctl/go.sum, components/ledger/go.mod, components/ledger/internal/api/v2/controllers_info_test.go, components/operator/internal/controllers/stack/testdata/monopod-disabled-one-service/results/configmaps--v1/search-benthos-streams.yaml, components/operator/internal/controllers/stack/testdata/monopod-latest/results/configmaps--v1/search-benthos-streams.yaml, components/operator/internal/controllers/stack/testdata/monopod-ledgerv1/results/configmaps--v1/search-benthos-streams.yaml, components/operator/internal/controllers/stack/testdata/monopod-search-before-v0.7.0/results/configmaps--v1/search-benthos-streams.yaml, components/operator/internal/controllers/stack/testdata/multipod-debug/results/configmaps--v1/search-benthos-streams.yaml, components/operator/internal/controllers/stack/testdata/multipod-disabled-one-service/results/configmaps--v1/search-benthos-streams.yaml, components/operator/internal/controllers/stack/testdata/multipod-latest-no-monitoring/results/configmaps--v1/search-benthos-streams.yaml, components/operator/internal/controllers/stack/testdata/multipod-latest/results/configmaps--v1/search-benthos-streams.yaml, components/operator/internal/controllers/stack/testdata/multipod-service-annotation/results/configmaps--v1/search-benthos-streams.yaml, components/orchestration/go.sum, components/wallets/go.sum
- feat: lint + tidy
- fix: tests
=> fix: tests

components/fctl/cmd/payments/accounts/balances.go, components/fctl/cmd/payments/accounts/list.go, components/fctl/cmd/payments/accounts/root.go, components/fctl/cmd/payments/accounts/show.go, components/fctl/cmd/payments/bankaccounts/create.go, components/fctl/cmd/payments/bankaccounts/list.go, components/fctl/cmd/payments/bankaccounts/root.go, components/fctl/cmd/payments/bankaccounts/show.go, components/fctl/cmd/payments/payments/root.go, components/fctl/cmd/payments/root.go, components/fctl/cmd/payments/transferinitiation/delete.go, components/fctl/cmd/payments/transferinitiation/list.go, components/fctl/cmd/payments/transferinitiation/retry.go, components/fctl/cmd/payments/transferinitiation/root.go, components/fctl/cmd/payments/transferinitiation/update_status.go, components/payments/openapi.yaml, docs/openapi/v2.json, openapi/build/generate.json
=> feat(fctl): fix/update payments endpoints

components/agent/Dockerfile, components/agent/go.mod, components/auth/Dockerfile, components/auth/go.mod, components/fctl/Dockerfile, components/fctl/go.mod, components/fctl/go.sum, components/gateway/Dockerfile, components/ledger/go.mod, components/operator/Dockerfile, components/orchestration/Dockerfile, components/orchestration/go.mod, components/payments/Dockerfile, components/payments/go.mod, components/search/Dockerfile, components/search/go.mod, components/stargate/Dockerfile, components/stargate/go.mod, components/wallets/Dockerfile, components/wallets/go.mod, components/webhooks/Dockerfile, components/webhooks/go.mod, go.mod
- Fix go.mod 1.19 -> 1.20 and bump dockerfile to 1.20
=> fix: comparable need go 1.20

components/operator/internal/controllers/stack/stack_reconciler.go, components/operator/internal/modules/module.go
Job status changed were not catched by the operator.
Fixes ENG-78
=> fix(operator): fix predicates with jobs

components/operator/helm/templates/deployment.yaml, components/operator/helm/values.yaml, components/operator/internal/controllers/stack/stack_reconciler.go, components/operator/main.go
=> fix: change wording !disable -> enable

components/payments/internal/app/api/bank_account.go, components/payments/internal/app/api/router.go, components/payments/internal/app/models/account.go, components/payments/internal/app/models/bank_account.go, components/payments/internal/app/storage/bank_accounts.go, components/payments/internal/app/storage/migrations.go, components/payments/openapi.yaml, docs/openapi/v2.json, openapi/build/generate.json
This PR does two things:
- Link Bank accounts to payment accounts
- Rename transfer-initiation to transfer-initiations
Fixes ENG-114
Fixes ENG-122
=> feat(payments): link bank accounts to payment accounts

components/fctl/cmd/payments/transferinitiation/list.go, components/fctl/cmd/payments/transferinitiation/show.go, components/orchestration/internal/workflow/activities/activity_payment_stripe_transfer.go, components/payments/internal/app/api/transfer_initiation.go, components/payments/internal/app/connectors/currencycloud/connector.go, components/payments/internal/app/connectors/mangopay/connector.go, components/payments/internal/app/connectors/modulr/connector.go, components/payments/internal/app/connectors/moneycorp/connector.go, components/payments/internal/app/connectors/stripe/connector.go, components/payments/internal/app/connectors/wise/connector.go, components/payments/internal/app/models/task.go, components/payments/internal/app/models/transfer_initiation.go, components/payments/internal/app/storage/migrations.go, components/payments/internal/app/storage/transfer_initiation.go, components/payments/internal/app/task/scheduler.go, components/payments/openapi.yaml, docs/openapi/v2.json, openapi/build/generate.json
Allow the user to schedule a payment in the future via tranfer initiations
Fixes ENG-130
=> feat(payments): add scheduled at for transfer initiations

components/payments/cmd/connectors/internal/api/transfer_initiation.go, components/payments/cmd/connectors/internal/connectors/bankingcircle/client/accounts.go, components/payments/cmd/connectors/internal/connectors/bankingcircle/client/payments.go, components/payments/cmd/connectors/internal/connectors/bankingcircle/client/transfer_payouts.go, components/payments/cmd/connectors/internal/connectors/bankingcircle/connector.go, components/payments/cmd/connectors/internal/connectors/bankingcircle/task_fetch_payments.go, components/payments/cmd/connectors/internal/connectors/bankingcircle/task_payments.go, components/payments/cmd/connectors/internal/connectors/bankingcircle/task_resolve.go
This PR adds transfers and payouts for Banking Circle connector
Fixes ENG-61
=> feat(payments): add transfers and payouts for banking-circle

.github/workflows/main.yml, .github/workflows/release.yml, components/ledger/internal/api/v2/controllers_accounts_test.go, components/ledger/internal/api/v2/controllers_balances_test.go, components/ledger/internal/api/v2/controllers_transactions_test.go, components/ledger/internal/api/v2/utils.go, tests/integration/internal/init.go, tests/integration/suite/ledger-list-transactions.go
=> feat: add stable cursor

Earthfile, components/ledger/Earthfile, components/ledger/internal/api/bulk/bulk.go, components/ledger/internal/api/v2/controllers_bulk.go, components/ledger/internal/api/v2/controllers_bulk_test.go, components/ledger/internal/api/v2/controllers_transactions_test.go, components/ledger/internal/api/v2/utils.go, components/ledger/internal/script.go, components/ledger/internal/storage/ledgerstore/balances.go, components/ledger/internal/storage/ledgerstore/balances_test.go, components/ledger/internal/storage/ledgerstore/transactions.go, components/ledger/internal/transaction.go, components/ledger/libs/pgtesting/postgres.go, components/orchestration/go.mod, components/orchestration/go.sum, libs/go-libs/migrations/migrator_test.go, openapi/build/generate.json, tests/integration/go.mod, tests/integration/go.sum, tests/integration/suite/ledger-aggregated-balances.go
=> feat: add balances aggregation by metadata

Earthfile, components/fctl/cmd/ledger/accounts/show.go, components/ledger/internal/account.go, components/ledger/libs/migrations/migrator_test.go, components/ledger/libs/pgtesting/postgres.go, components/ledger/openapi.yaml, components/orchestration/go.mod, components/orchestration/go.sum, components/orchestration/internal/workflow/activities/activity_account_get.go, components/orchestration/internal/workflow/stages/send/run_test.go, libs/go-libs/migrations/migrator_test.go, openapi/build/generate.json, tests/integration/suite/ledger-create-transaction.go, tests/integration/suite/ledger-list-count-accounts.go, tests/integration/suite/ledger-set-metadata-on-account.go
=> fix: support of 'expand' on accounts list

components/fctl/cmd/ledger/transactions/revert.go, components/ledger/internal/api/backend/backend.go, components/ledger/internal/api/backend/backend_generated.go, components/ledger/internal/api/bulk/bulk.go, components/ledger/internal/api/v1/controllers_transactions.go, components/ledger/internal/api/v1/controllers_transactions_test.go, components/ledger/internal/api/v2/controllers_bulk_test.go, components/ledger/internal/api/v2/controllers_transactions.go, components/ledger/internal/api/v2/controllers_transactions_test.go, components/ledger/internal/engine/command/commander.go, components/ledger/internal/engine/command/commander_test.go, components/ledger/internal/engine/ledger.go, components/ledger/internal/errors.go, components/ledger/internal/machine/internal/funding.go, components/ledger/internal/machine/machine.go, components/ledger/internal/machine/machine_test.go, components/ledger/internal/machine/vm/errors.go, components/ledger/internal/machine/vm/machine.go, components/ledger/internal/machine/vm/machine_overdraft_test.go, components/ledger/internal/machine/vm/machine_test.go, components/ledger/internal/numscript.go, components/ledger/internal/storage/inmemory.go, components/ledger/internal/storage/ledgerstore/balances_test.go, components/ledger/internal/transaction.go, components/ledger/openapi.yaml, components/orchestration/internal/workflow/activities/activity_ledger_revert_transaction.go, openapi/build/generate.json, tests/integration/internal/service.go, tests/integration/suite/ledger-revert-transaction.go
=> feat: add 'force' query param to force reverts even if the source accounts does not have enough funds

components/operator/internal/modules/service.go
=> fix: missing connection close

components/fctl/cmd/ledger/internal/print.go, components/fctl/cmd/ledger/internal/transaction.go, components/fctl/cmd/ledger/transactions/revert.go, components/ledger/internal/machine/vm/machine_overdraft_test.go, components/ledger/openapi.yaml, openapi/build/generate.json, tests/integration/suite/ledger-create-bulk.go, tests/integration/suite/ledger-create-transaction.go, tests/integration/suite/ledger-list-logs.go, tests/integration/suite/ledger-list-transactions.go, tests/integration/suite/ledger-revert-transaction.go, tests/integration/suite/ledger-set-metadata-on-transaction.go, tests/integration/suite/orchestration-workflows-execute.go
=> fix: missing big ints un openapispec / sdk

components/ledger/internal/machine/vm/machine.go, components/ledger/internal/machine/vm/machine_test.go
=> fix: import from https://github.com/formancehq/ledger/pull/454/files

.github/workflows/main.yml, components/ledger/internal/storage/ledgerstore/accounts.go, components/ledger/internal/storage/ledgerstore/accounts_test.go, components/ledger/internal/storage/ledgerstore/balances.go, components/ledger/internal/storage/ledgerstore/logs.go, components/ledger/internal/storage/ledgerstore/migrations/0-init-schema.sql, components/ledger/internal/storage/ledgerstore/transactions.go, components/ledger/internal/storage/ledgerstore/transactions_test.go
Not optimized, the 'ledger' column will be included in a partition in a later PR.
Fixes ENG-227
=> feat(ledger): add 'ledger' column on all tables

components/payments/cmd/api/internal/storage/accounts_test.go, components/payments/cmd/api/internal/storage/balances.go, components/payments/cmd/api/internal/storage/balances_test.go, components/payments/cmd/api/internal/storage/connectors_test.go, components/payments/cmd/api/internal/storage/main_test.go, components/payments/cmd/api/internal/storage/module.go, components/payments/cmd/api/internal/storage/repository.go, components/payments/cmd/connectors/internal/storage/balances.go
=> feat(payments): allow user to request balance in the past

components/ledger/Earthfile, components/ledger/internal/api/backend/backend.go, components/ledger/internal/api/backend/backend_generated.go, components/ledger/internal/api/v1/controllers_accounts.go, components/ledger/internal/api/v1/controllers_balances.go, components/ledger/internal/api/v1/controllers_info.go, components/ledger/internal/api/v1/controllers_transactions.go, components/ledger/internal/api/v2/controllers_accounts.go, components/ledger/internal/api/v2/controllers_info.go, components/ledger/internal/api/v2/controllers_transactions.go, components/ledger/internal/engine/ledger.go, components/ledger/internal/storage/ledgerstore/accounts.go, components/ledger/internal/storage/ledgerstore/balances.go, components/ledger/internal/storage/ledgerstore/logs.go, components/ledger/internal/storage/ledgerstore/logs_test.go, components/ledger/internal/storage/ledgerstore/main_test.go, components/ledger/internal/storage/ledgerstore/store_benchmarks_test.go, components/ledger/internal/storage/ledgerstore/transactions.go, components/ledger/internal/storage/sqlutils/utils.go, components/ledger/libs/bun/bunexplain/explain_hook.go, libs/go-libs/bun/bunexplain/explain_hook.go, tests/benchmarks/Earthfile, tests/benchmarks/extension/extension.go
- feat: bench logs insertion
- feat: bench list
=> feat: benchmarks store

components/auth/openapi.yaml
=> feat(openapi): add oidc discovery

components/agent/internal/k8s/k8s.go, components/auth/cmd/serve.go, components/ledger/libs/otlp/http_client.go, components/orchestration/cmd/worker.go, components/search/cmd/serve.go, components/search/go.mod, components/wallets/cmd/serve.go, libs/go-libs/otlp/http_client.go
=> feat(otlp): add bodies on http requests if status code >= 400

components/payments/cmd/connectors/internal/connectors/stripe/client/balances.go, components/payments/cmd/connectors/internal/connectors/stripe/config.go, components/payments/cmd/connectors/internal/connectors/stripe/loader.go, components/payments/cmd/connectors/internal/connectors/stripe/task_fetch_accounts.go, components/payments/cmd/connectors/internal/connectors/stripe/task_fetch_balances.go, components/payments/cmd/connectors/internal/connectors/stripe/task_fetch_payments.go, components/payments/cmd/connectors/internal/connectors/stripe/task_resolve.go, components/payments/cmd/connectors/internal/connectors/stripe/translate.go
=> fix(stripe): add missing root account information

components/orchestration/openapi.yaml, components/wallets/openapi.yaml, openapi/build/generate.json
=> fix: duplicate components definition for orchestration

components/payments/cmd/connectors/internal/api/connectormodule.go, components/payments/cmd/connectors/internal/api/connectors_manager/connector_test.go, components/payments/cmd/connectors/internal/api/connectors_manager/manager.go, components/payments/cmd/connectors/internal/api/module.go, components/payments/cmd/connectors/internal/api/service/bank_account.go, components/payments/cmd/connectors/internal/api/service/bank_account_test.go, components/payments/cmd/connectors/internal/api/service/service.go, components/payments/cmd/connectors/internal/api/service/transfer_initiation.go, components/payments/cmd/connectors/internal/api/service/transfer_initiation_test.go, components/payments/cmd/connectors/internal/connectors/bankingcircle/connector.go, components/payments/cmd/connectors/internal/connectors/bankingcircle/task_create_external_account.go, components/payments/cmd/connectors/internal/connectors/bankingcircle/task_fetch_accounts.go, components/payments/cmd/connectors/internal/connectors/bankingcircle/task_resolve.go, components/payments/cmd/connectors/internal/connectors/connector.go, components/payments/cmd/connectors/internal/connectors/currencycloud/connector.go, components/payments/cmd/connectors/internal/connectors/dummypay/connector.go, components/payments/cmd/connectors/internal/connectors/errors.go, components/payments/cmd/connectors/internal/connectors/mangopay/connector.go, components/payments/cmd/connectors/internal/connectors/modulr/connector.go, components/payments/cmd/connectors/internal/connectors/moneycorp/connector.go, components/payments/cmd/connectors/internal/connectors/stripe/connector.go, components/payments/cmd/connectors/internal/connectors/wise/connector.go, components/payments/cmd/connectors/internal/ingestion/bank_account.go, components/payments/cmd/connectors/internal/ingestion/ingester.go, components/payments/cmd/connectors/internal/storage/repository.go
=> feat(payments): link bank account creation with connectors

components/operator/.earthly/configuration/templates/configuration.yaml, components/operator/internal/controllers/stack/testdata/multipod-with-audit-log-unvalid-tag/results/configmaps--v1/search-benthos-audit.yaml, components/operator/internal/controllers/stack/testdata/multipod-with-audit-log-unvalid-tag/results/deployments-apps-v1/search-benthos.yaml, components/operator/internal/controllers/stack/testdata/multipod-with-audit-log/results/configmaps--v1/search-benthos-audit.yaml, components/operator/internal/controllers/stack/testdata/multipod-with-audit-log/results/deployments-apps-v1/search-benthos.yaml, components/operator/internal/modules/search/benthos/audit/gateway_audit.yaml
* due to changes in es resources.yaml
=> fix: benthos not sending request to ES

components/ledger/internal/storage/ledgerstore/balances.go, components/ledger/internal/storage/ledgerstore/balances_test.go
=> fix: balances aggregation

components/payments/cmd/connectors/internal/ingestion/accounts.go, components/payments/cmd/connectors/internal/ingestion/balances.go, components/payments/cmd/connectors/internal/ingestion/bank_account.go, components/payments/cmd/connectors/internal/ingestion/ingester.go, components/payments/cmd/connectors/internal/ingestion/ingester_test.go, components/payments/cmd/connectors/internal/ingestion/payments.go, components/payments/cmd/connectors/internal/ingestion/payments_test.go, components/payments/cmd/connectors/internal/ingestion/transfer_initiation.go, components/payments/cmd/connectors/internal/storage/payments.go, components/payments/cmd/connectors/internal/storage/payments_test.go, components/payments/internal/models/payment.go
=> feat(payments): do not publish payments if no update

ee/orchestration/cmd/root.go, ee/orchestration/cmd/worker.go, ee/orchestration/internal/triggers/listener.go, ee/orchestration/internal/triggers/module.go
- fix: triggers with metadata
- fix: include stack in workflows ids
=> fix: include stack id in workflows ids

components/payments/cmd/connectors/internal/connectors/adyen/client/accounts.go, components/payments/cmd/connectors/internal/connectors/adyen/connector.go, components/payments/cmd/connectors/internal/connectors/adyen/task_fetch_merchants_accounts.go, components/payments/cmd/connectors/internal/connectors/adyen/task_main.go, components/payments/cmd/connectors/internal/connectors/adyen/task_resolve.go
=> feat(payments): add adyen merchants account fetching

ee/reconciliation/go.mod, ee/reconciliation/go.sum, ee/reconciliation/internal/api/service/reconciliation.go, ee/reconciliation/internal/api/service/utils.go, ee/reconciliation/internal/api/service/utils_test.go
=> feat(reconciliation): check versions

ee/stargate/internal/server/grpc/api.go
=> feat(stargate): more precise metrics for grpc latencies

components/operator/internal/controllers/stack/testdata/monopod-disabled-one-service/results/deployments-apps-v1/monopod-disabled-one-service.yaml, components/operator/internal/controllers/stack/testdata/monopod-latest/results/deployments-apps-v1/monopod-latest.yaml, components/operator/internal/controllers/stack/testdata/monopod-ledgerv1/results/deployments-apps-v1/monopod-ledgerv1.yaml, components/operator/internal/controllers/stack/testdata/monopod-payments-after-v1.0.0-alpha.6/results/deployments-apps-v1/monopod-payments-after-v1-0-0-alpha-6.yaml, components/operator/internal/controllers/stack/testdata/monopod-payments-before-v1.0.0-alpha.6/results/deployments-apps-v1/monopod-payments-before-v1-0-0-alpha-6.yaml, components/operator/internal/controllers/stack/testdata/monopod-search-before-v0.7.0/results/deployments-apps-v1/monopod-search-before-v0-7-0.yaml, components/operator/internal/modules/pod.go
=> fix(operator): auto reboot of monopods on configs changes

components/payments/cmd/connectors/internal/connectors/duration.go
=> fix(payments): fix marshal when getting connector config

components/fctl/cmd/cloud/organizations/users/update.go
- feat: generate membership client from earthly
- fix: fctl
=> fix: fctl membership client

components/payments/cmd/connectors/internal/connectors/stripe/task_payments.go
=> feat(payments): fix stripe transfer payment id linked

components/payments/cmd/connectors/internal/api/bank_account.go, components/payments/cmd/connectors/internal/api/service/bank_account.go, components/payments/cmd/connectors/internal/api/service/service.go, components/payments/cmd/connectors/internal/api/service/service_test.go, components/payments/cmd/connectors/internal/connectors/atlar/connector.go, components/payments/cmd/connectors/internal/connectors/atlar/task_create_external_bank_account.go, components/payments/cmd/connectors/internal/storage/bank_accounts.go, components/payments/cmd/connectors/internal/storage/bank_accounts_test.go, components/payments/openapi.yaml, libs/clients/go/docs/models/shared/bankaccount.md, libs/clients/go/pkg/models/shared/bankaccount.go
=> feat(payment): add linked account when creating a bank account

components/fctl/cmd/orchestration/triggers/occurrences/list.go, ee/orchestration/internal/triggers/manager.go, ee/orchestration/internal/triggers/trigger.go, ee/orchestration/internal/workflow/instance.go, ee/orchestration/openapi.yaml, ee/orchestration/openapi/v1.yaml, ee/orchestration/openapi/v2.yaml, libs/clients/go/docs/models/errors/v2errorerrorcode.md, libs/clients/go/docs/models/shared/errorerrorcode.md, libs/clients/go/docs/models/shared/triggeroccurrence.md, libs/clients/go/docs/models/shared/v2errorerrorcode.md, libs/clients/go/docs/models/shared/v2triggeroccurrence.md, libs/clients/go/pkg/models/sdkerrors/v2error.go, libs/clients/go/pkg/models/shared/error.go, libs/clients/go/pkg/models/shared/triggeroccurrence.go, libs/clients/go/pkg/models/shared/v2error.go, libs/clients/go/pkg/models/shared/v2triggeroccurrence.go, tests/integration/internal/modules/orchestration.go, tests/integration/suite/orchestration-triggers.go
=> feat(flows): add instance status on triggers

components/fctl/cmd/cloud/regions/list.go, components/fctl/cmd/stack/create.go
=> feat(fctl): allow to select versions on stack creation

ee/auth/cmd/serve.go, ee/auth/pkg/api/authorization/accesstoken_test.go, ee/auth/pkg/oidc/module.go, ee/auth/pkg/oidc/oidc_test.go, ee/auth/pkg/oidc/provider.go, ee/auth/pkg/oidc/router.go
=> feat: make auth delegation optional

components/payments/cmd/connectors/internal/connectors/modulr/client/accounts.go, components/payments/cmd/connectors/internal/connectors/modulr/client/beneficiaries.go, components/payments/cmd/connectors/internal/connectors/modulr/client/transactions.go, components/payments/cmd/connectors/internal/connectors/modulr/config.go, components/payments/cmd/connectors/internal/connectors/modulr/connector.go, components/payments/cmd/connectors/internal/connectors/modulr/loader.go, components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_accounts.go, components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_beneficiaries.go, components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_transactions.go, components/payments/cmd/connectors/internal/connectors/modulr/task_resolve.go
=> fix(payments): fix missing modulr pagination

ee/wallets/pkg/api/router.go
Content type should be application json instead of text plain
Fixes ENG-462
=> fix(wallets): fix ts sdk failing on get-info

components/payments/cmd/connectors/internal/api/service/transfer_initiation.go, components/payments/cmd/connectors/internal/api/service/transfer_initiation_test.go, components/payments/cmd/connectors/internal/api/transfer_initiation_test.go, components/payments/internal/storage/migrations_v1.x.go
=> feat(payments): allow transfer description to be empty

components/ledger/libs/api/utils.go, libs/go-libs/api/utils.go
- fix: missing struct in accepted
- fix: pre-commit
=> fix: missing baseResponse in Accepted helper

components/fctl/cmd/cloud/organizations/update.go
=> fix: fctl cloud organizations update

components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_accounts.go, components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_beneficiaries.go, components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_transactions.go, components/payments/cmd/connectors/internal/connectors/modulr/task_resolve.go, components/payments/cmd/connectors/internal/storage/payments.go, components/payments/cmd/connectors/internal/storage/payments_test.go
=> fix(payments): fix modulr timestamps

components/payments/cmd/connectors/internal/api/connectormodule.go, components/payments/cmd/connectors/internal/connectors/adyen/task_standard_webhooks.go, components/payments/cmd/connectors/internal/connectors/atlar/task_fetch_transactions.go, components/payments/cmd/connectors/internal/connectors/bankingcircle/task_fetch_payments.go, components/payments/cmd/connectors/internal/connectors/currencycloud/task_fetch_transactions.go, components/payments/cmd/connectors/internal/connectors/dummypay/connector_test.go, components/payments/cmd/connectors/internal/connectors/dummypay/task_ingest.go, components/payments/cmd/connectors/internal/connectors/dummypay/task_init_directory.go, components/payments/cmd/connectors/internal/connectors/mangopay/task_fetch_transactions.go, components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_transactions.go, components/payments/cmd/connectors/internal/connectors/moneycorp/task_fetch_transactions.go, components/payments/cmd/connectors/internal/connectors/stripe/task_fetch_payments_for_connected_account.go, components/payments/cmd/connectors/internal/connectors/wise/task_fetch_transfers.go, components/payments/cmd/connectors/internal/ingestion/ingester.go, components/payments/cmd/connectors/internal/ingestion/payments.go, components/payments/cmd/connectors/internal/ingestion/payments_test.go, components/payments/cmd/connectors/internal/ingestion/task.go, components/payments/cmd/connectors/internal/task/scheduler.go, components/payments/cmd/connectors/internal/task/scheduler_test.go, components/payments/go.mod, components/payments/go.sum
=> feat(payments): small improvments + worker pool

components/fctl/cmd/payments/bankaccounts/list.go, components/fctl/cmd/payments/bankaccounts/show.go, components/payments/cmd/api/internal/api/bank_accounts.go, components/payments/cmd/api/internal/api/bank_accounts_test.go, components/payments/cmd/connectors/internal/api/bank_account.go, components/payments/cmd/connectors/internal/api/bank_account_test.go, components/payments/cmd/connectors/internal/connectors/mangopay/client/bank_accounts.go, components/payments/cmd/connectors/internal/connectors/mangopay/client/metadata.go, components/payments/cmd/connectors/internal/connectors/mangopay/connector.go, components/payments/cmd/connectors/internal/connectors/mangopay/task_create_external_bank_account.go, components/payments/cmd/connectors/internal/connectors/mangopay/task_resolve.go, components/payments/cmd/connectors/internal/storage/bank_accounts.go, components/payments/openapi.yaml, releases/sdks/go/.speakeasy/gen.lock, releases/sdks/go/docs/pkg/models/shared/bankaccount.md, releases/sdks/go/pkg/models/shared/bankaccount.go
=> feat(payments): add mangopay bank accounts creation

components/payments/cmd/connectors/internal/connectors/moneycorp/client/accounts.go, components/payments/cmd/connectors/internal/connectors/moneycorp/client/balances.go, components/payments/cmd/connectors/internal/connectors/moneycorp/client/recipients.go, components/payments/cmd/connectors/internal/connectors/moneycorp/client/transactions.go, components/payments/cmd/connectors/internal/connectors/moneycorp/config.go, components/payments/cmd/connectors/internal/connectors/moneycorp/task_fetch_accounts.go, components/payments/cmd/connectors/internal/connectors/moneycorp/task_fetch_recipients.go, components/payments/cmd/connectors/internal/connectors/moneycorp/task_fetch_transactions.go, components/payments/cmd/connectors/internal/connectors/moneycorp/task_resolve.go, components/payments/cmd/connectors/internal/connectors/stripe/translate.go, components/payments/cmd/connectors/internal/task/scheduler.go
=> feat(payments): improve moneycorp connector by adding state

components/operator/api/formance.com/v1beta1/gatewayhttpapi_types.go, components/operator/config/crd/bases/formance.com_gatewayhttpapis.yaml, components/operator/internal/resources/gatewayhttpapis/create.go, components/operator/internal/resources/gateways/Caddyfile.gotpl, components/operator/internal/resources/payments/controller.go, components/operator/internal/tests/testdata/resources/gateway-controller/configmap-with-audit.yaml, components/operator/internal/tests/testdata/resources/gateway-controller/configmap-with-ledger-and-another-service.yaml, components/operator/internal/tests/testdata/resources/gateway-controller/configmap-with-ledger-and-auth.yaml, components/operator/internal/tests/testdata/resources/gateway-controller/configmap-with-ledger-only.yaml, components/operator/internal/tests/testdata/resources/gateway-controller/configmap-with-opentelemetry.yaml
- fix(operator): payments healthcheck
- fix(operator): payments health checks
=> fix(operator): payments health checks

components/payments/cmd/connectors/internal/connectors/modulr/client/accounts.go, components/payments/cmd/connectors/internal/connectors/modulr/client/beneficiaries.go, components/payments/cmd/connectors/internal/connectors/modulr/client/transactions.go, components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_accounts.go, components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_beneficiaries.go, components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_transactions.go, components/payments/cmd/connectors/internal/connectors/modulr/task_main.go, components/payments/cmd/connectors/internal/connectors/modulr/task_resolve.go
=> feat(payments): make Modulr connector stateful

components/payments/cmd/connectors/internal/connectors/mangopay/client/metadata.go, components/payments/cmd/connectors/internal/connectors/mangopay/task_create_external_bank_account.go, components/payments/internal/models/bank_account.go, components/payments/internal/models/metadata.go
=> feat(payments): improve bank accounts metadata keys

components/operator/internal/resources/databases/controller.go, components/operator/internal/resources/settings/helpers.go, components/operator/internal/tests/database_controller_test.go
=> feat(operator): add settings 'clear-database' allowing to prevent databases from being deleted

components/ledger/internal/api/backend/resolver.go, components/ledger/libs/api/utils.go, components/ledger/openapi.yaml, components/ledger/openapi/v2.yaml, libs/go-libs/api/utils.go, releases/sdks/go/.speakeasy/gen.lock, releases/sdks/go/docs/pkg/models/shared/v2errorsenum.md, releases/sdks/go/formance.go, releases/sdks/go/gen.yaml, releases/sdks/go/pkg/models/shared/v2errorsenum.go, tests/integration/suite/ledger-list-transactions.go
=> feat(ledger): add LEDGER_NOT_FOUND error code

components/operator/.earthly/configuration/templates/settings.yaml, components/operator/internal/resources/databases/controller.go, components/operator/internal/tests/database_controller_test.go
- feat(operator): add settings to prevent database clean
- feat(operator): add settings to avoid deleting databases
=> feat(operator): clear database settings

ee/agent/internal/informer_stacks.go, ee/agent/tests/informers_stacks_test.go
- fix: status changed when reconcilling disabled stack where it should not
=> fix: status change when the stack is disabled (Disabled -> Progressing -> Disabled)

ee/gateway/pkg/plugins/audit.go
=> fix(gateway): stop caddy on nats disconnection

ee/agent/internal/informer_stacks.go, ee/agent/tests/informers_stacks_test.go
- fix: sending status when status (disable || ready) change
=> fix: status not sent when disabled is changed

components/payments/cmd/connectors/internal/connectors/mangopay/task_fetch_wallets.go
Since we want the balance history and since balances are only inside wallets, we cannot have a state for the wallets fetching task.
Fixes ENG-617
=> fix(payments): mangopay balances

components/operator/internal/resources/deployments/deployments.go, components/operator/internal/resources/ledgers/deployments.go, components/operator/internal/resources/payments/deployments.go, components/operator/internal/resources/settings/caddy.go, components/operator/internal/tests/ledger_controller_test.go
=> feat: make payments/ledger gateways use caddy image

components/payments/cmd/connectors/internal/connectors/currencycloud/client/accounts.go, components/payments/cmd/connectors/internal/connectors/currencycloud/client/balances.go, components/payments/cmd/connectors/internal/connectors/currencycloud/client/beneficiaries.go, components/payments/cmd/connectors/internal/connectors/currencycloud/client/transactions.go, components/payments/cmd/connectors/internal/connectors/currencycloud/task_fetch_accounts.go, components/payments/cmd/connectors/internal/connectors/currencycloud/task_fetch_beneficiaries.go, components/payments/cmd/connectors/internal/connectors/currencycloud/task_fetch_transactions.go
=> feat(payments): improve currencycloud states

ee/stargate/internal/server/grpc/api_test.go
We are sending ping from the server every x seconds. If the test takes times, we can receive a ping and thus crashing because the cast fails.
=> fix(stargate): fix tests

components/operator/internal/core/controllers.go, components/operator/internal/core/reconciler.go, components/operator/internal/resources/auths/configuration.go, components/operator/internal/resources/auths/controller.go, components/operator/internal/resources/deployments/deployments.go, components/operator/internal/resources/gateways/controller.go, components/operator/internal/resources/ledgers/controller.go, components/operator/internal/resources/payments/controller.go, components/operator/internal/tests/auth_controller_test.go, components/operator/internal/tests/database_controller_test.go
=> feat(operator): remove objects on disabled stacks

components/operator/internal/resources/deployments/deployments.go
=> feat(operator): make configurable replicas

components/operator/.earthly/configuration/templates/settings.yaml, components/operator/README.md
=> feat(operator): document actual settings

ee/agent/internal/module.go
=> fix: informers are run syncrhonously

components/operator/Earthfile, components/operator/internal/resources/gateways/Caddyfile.gotpl, components/operator/internal/resources/gateways/deployment.go, components/operator/internal/resources/settings/caddy.go, components/operator/internal/tests/testdata/resources/gateway-controller/configmap-with-audit.yaml, components/operator/internal/tests/testdata/resources/gateway-controller/configmap-with-ledger-and-another-service.yaml, components/operator/internal/tests/testdata/resources/gateway-controller/configmap-with-ledger-and-auth.yaml, components/operator/internal/tests/testdata/resources/gateway-controller/configmap-with-ledger-only.yaml, components/operator/internal/tests/testdata/resources/gateway-controller/configmap-with-opentelemetry.yaml
=> feat(operator): Add metrics for gateway

components/ledger/libs/publish/cli.go, ee/stargate/cmd/root.go, libs/go-libs/publish/cli.go
=> feat(stargate): nats default max reconnect to infinite

components/fctl/cmd/stack/controller.go, components/fctl/cmd/stack/create.go, components/fctl/cmd/stack/restore.go, components/fctl/cmd/stack/upgrade.go
- **feat: reduce wait time**
- **fix: wrong check**
=> feat: wrong status ready check (wrong structure)

components/operator/api/formance.com/v1beta1/stack_types.go, components/operator/internal/resources/stacks/controller.go, ee/agent/internal/informer_stacks.go, ee/agent/tests/informers_stacks_test.go
- **feat: add retrieval of expected modules**
- **feat: ready on expected modules ready**
=> feat: first expected modules notion

components/ledger/libs/pgtesting/postgres.go, components/operator/internal/tests/internal/bootstrap.go, ee/orchestration/internal/storage/main_test.go, ee/orchestration/internal/storage/migrations.go, ee/orchestration/internal/storage/migrations_test.go, ee/orchestration/internal/workflow/config.go, ee/orchestration/internal/workflow/stage.go, libs/go-libs/pgtesting/postgres.go
Global note : The history endpoints will return only last run.
=> feat(orchestration): allow to reset temporal workflows

components/payments/cmd/api/internal/api/accounts.go, components/payments/cmd/api/internal/api/balances.go, components/payments/cmd/api/internal/api/balances_test.go, components/payments/cmd/api/internal/api/bank_accounts.go, components/payments/cmd/api/internal/api/bank_accounts_test.go, components/payments/cmd/api/internal/api/metadata.go, components/payments/cmd/api/internal/api/payments.go, components/payments/cmd/api/internal/api/payments_test.go, components/payments/cmd/api/internal/api/pools.go, components/payments/cmd/api/internal/api/pools_test.go, components/payments/cmd/api/internal/api/transfer_initiation.go, components/payments/cmd/api/internal/api/transfer_initiation_test.go
=> feat(payments): add api traces

components/payments/cmd/api/internal/storage/accounts.go, components/payments/cmd/api/internal/storage/balances.go, components/payments/cmd/api/internal/storage/bank_accounts.go, components/payments/cmd/api/internal/storage/payments.go, components/payments/cmd/api/internal/storage/pools.go, components/payments/cmd/api/internal/storage/transfer_initiation.go
=> fix(payments): fix sort query param

components/fctl/cmd/stack/controller.go
=> fix: wrong param pass to function

components/payments/cmd/connectors/internal/task/errors.go, components/payments/cmd/connectors/internal/task/scheduler.go, components/payments/cmd/connectors/internal/task/scheduler_test.go, components/payments/cmd/connectors/internal/task/storememory.go
=> feat(payments): add system to retry task or not

components/payments/cmd/connectors/internal/ingestion/payments.go, components/payments/cmd/connectors/internal/storage/payments.go, components/payments/internal/models/payment.go
=> fix(payments): fix missing metadata in postgres

ee/agent/internal/membership_listener.go, ee/agent/tests/membership_listener_test.go
=> fix: agent loop

components/payments/cmd/connectors/internal/connectors/modulr/client/accounts.go, components/payments/cmd/connectors/internal/connectors/modulr/task_fetch_accounts.go
=> fix(payments): no states for accounts and balances for modulr

releases/base.yaml
This change:
- replace the absolute token url with relative ones
- add security scopes to all operation
- list all scopes in the security scheme
=> feat(openapi): Configure the OpenAPI schema to fit the client credentials OAI spec

components/ledger/internal/storage/ledgerstore/transactions.go, components/ledger/internal/storage/ledgerstore/transactions_test.go, libs/go-libs/query/expression.go, libs/go-libs/query/expression_test.go, tests/integration/suite/ledger-list-count-accounts.go, tests/integration/suite/ledger-list-transactions.go
=> feat(libs): add  filter on query package

components/ledger/cmd/buckets.go
=> fix(ledger): segfault when error initializing storage driver

ee/agent/internal/membership_client.go
- **feat: send capabilities EE**
=> feat(agent): send capabilities throught metadata

components/ledger/openapi.yaml, components/ledger/openapi/v1.yaml, releases/sdks/go/.speakeasy/gen.lock, releases/sdks/go/formance.go, releases/sdks/go/gen.yaml, releases/sdks/go/ledger.go
=> fix(fctl): revert transaction returns empty error

components/ledger/Earthfile, components/ledger/internal/api/v2/controllers_accounts_test.go, components/ledger/internal/api/v2/controllers_balances_test.go, components/ledger/internal/api/v2/controllers_transactions_test.go, components/ledger/internal/api/v2/controllers_volumes_test.go, components/ledger/internal/storage/ledgerstore/accounts.go, components/ledger/internal/storage/ledgerstore/accounts_test.go, components/ledger/internal/storage/ledgerstore/balances.go, components/ledger/internal/storage/ledgerstore/balances_test.go, components/ledger/internal/storage/ledgerstore/transactions.go, components/ledger/internal/storage/ledgerstore/transactions_test.go, components/ledger/internal/storage/ledgerstore/volumes.go, components/ledger/internal/storage/ledgerstore/volumes_test.go, components/operator/internal/resources/brokers/reconcile.go, components/operator/tools/kubectl-stacks/list.go, ee/agent/internal/membership_listener.go, libs/go-libs/query/expression.go
=> feat(ledger): ENG-986 - Ability to filter-on-a-metadata-existence

ee/agent/internal/membership_listener.go, ee/agent/internal/module.go
=> fix: insensive value between kind and module.name

components/ledger/internal/api/v2/utils.go
=> feat: handle query param  for searching

ee/agent/internal/membership_listener.go, ee/agent/internal/membership_listener_test.go
- **fix: module singularization**
=> fix: use restMapping singularizer

components/fctl/membership-swagger.yaml, components/fctl/membershipclient/api/openapi.yaml
- **fix: enum are in upper case**
=> fix: invitations enums

components/operator/internal/resources/ledgers/init.go, components/operator/internal/resources/ledgers/reindex.go, components/operator/internal/tests/ledger_controller_test.go
=> fix(operator): remove ledger reindex job if search is not enabled

.github/workflows/main.yml, Earthfile
- **fix: auto deploy in staging**
=> fix: auto deploy in staging env

Earthfile, components/operator/cmd/main.go, components/operator/helm/operator/templates/deployment.yaml, components/operator/internal/core/platform.go, components/operator/internal/resources/databases/init.go, components/operator/tools/utils/Earthfile
=> chore: use operator version to discover utils version

components/operator/api/formance.com/v1beta1/shared.go, components/operator/internal/core/controllers.go, components/operator/internal/core/reconciler.go, components/operator/internal/tests/stack_controller_test.go
=> fix(operator): stacks annotations watching

components/payments/cmd/api/internal/api/module.go, components/payments/cmd/api/internal/storage/payments.go
=> feat(payments): add more filters for query payments

components/operator/README.md, components/operator/internal/resources/gateways/ingress.go, components/operator/internal/tests/gateway_controller_test.go
=> feat(operator): allow configure ingress annotations using a setting

components/ledger/internal/machine/script/compiler/compiler.go, components/ledger/internal/machine/script/compiler/compiler_test.go
Fixes https://github.com/formancehq/stack/issues/1473
=> fix: unexpected panic when allotment sum is not 1

ee/agent/.earthly/values.yaml, ee/agent/helm/templates/_helpers.tpl, ee/agent/helm/templates/deployment.yaml, ee/agent/helm/values.yaml
=> feat(agent): add configurable logging format

components/operator/Earthfile, ee/agent/Earthfile, helm/Earthfile, helm/demo/Earthfile, helm/regions/Earthfile
- **fix: regions is package witout operators crd sub chart**
- **feat: save artifact**
=> fix: regions is packaged witout operator-crds sub chart

components/ledger/cmd/root.go, components/operator/README.md, components/operator/api/formance.com/v1beta1/settings_types.go, components/operator/config/crd/bases/formance.com_settings.yaml, components/operator/docs/crd.md, components/operator/helm/crds/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_settings.formance.com.yaml, components/operator/internal/resources/applications/application.go
=> feat(operator): configure json logging on services

components/operator/tools/kubectl-stacks/main.go, components/operator/tools/kubectl-stacks/settings.go
=> feat(kubectl-stacks): add settings edition

components/operator/Earthfile, components/operator/cmd/main.go, components/operator/helm/operator/templates/deployment.yaml, components/operator/helm/operator/values.yaml
=> feat(operator): enable json log by default

ee/webhooks/pkg/storage/postgres/postgres.go
=> fix(webhooks): retries on deleted configs

components/payments/cmd/connectors/internal/connectors/atlar/client/transactions.go, components/payments/cmd/connectors/internal/connectors/atlar/task_fetch_transactions.go, components/payments/cmd/connectors/internal/connectors/atlar/task_payments.go, components/payments/docker-compose.yml
=> fix(payments): wrong related payment ids

libs/go-libs/query/expression.go, tests/integration/suite/ledger-list-transactions.go
=> fix(ledger): cursor marshalling

components/fctl/cmd/stack/modules/disable.go, components/fctl/cmd/stack/modules/enable.go
=> fix(fctl): mandatory flag --stack on modules (de)activation

components/ledger/internal/engine/command/commander.go, tests/integration/suite/ledger-create-transaction.go
=> fix(ledger): dry run mode

ee/wallets/pkg/api/handler_holds_confirm_test.go, ee/wallets/pkg/api/handler_holds_get_test.go, ee/wallets/pkg/api/handler_holds_void_test.go, ee/wallets/pkg/api/handler_transactions_list_test.go, ee/wallets/pkg/api/handler_wallets_credit_test.go, ee/wallets/pkg/api/handler_wallets_debit_test.go, ee/wallets/pkg/api/utils_test.go, ee/wallets/pkg/hold.go, ee/wallets/pkg/ledger_interface.go, ee/wallets/pkg/manager.go, ee/wallets/pkg/module.go, ee/wallets/pkg/transaction.go, tests/integration/suite/wallets-debit.go
=> chore(wallets): migrate under ledger v2

components/payments/cmd/api/internal/storage/payments.go, components/payments/cmd/connectors/internal/storage/metadata.go, components/payments/internal/storage/migrations_v1.x.go
=> fix(payments): add migration to remove duplicates in changelogs

components/payments/internal/messages/accounts.go, ee/search/benthos/streams/payments/payments.yaml
=> feat(payments): add raw data for accounts

components/payments/cmd/connectors/internal/connectors/stripe/task_fetch_accounts.go
=> feat(payments): add stripe account connect metadata

ee/orchestration/internal/workflow/activities/activity.go, ee/orchestration/internal/workflow/activities/activity_ledger_add_account_metadata.go, ee/orchestration/internal/workflow/activities/activity_ledger_create_transaction.go, ee/orchestration/internal/workflow/activities/activity_wallet_confirm_hold.go, ee/orchestration/internal/workflow/activities/activity_wallet_credit.go, ee/orchestration/internal/workflow/activities/activity_wallet_debit.go, ee/orchestration/internal/workflow/activities/activity_wallet_void_hold.go
=> feat(orchestration): use iks for wallets interactions

ee/reconciliation/internal/api/service/reconciliation.go, ee/reconciliation/internal/api/service/reconciliation_test.go
Assets missing and assets at 0 should be considered equivalent when doing reconciliation.
Fixes ENG-1175
=> fix(reconciliation): fix missing payments balances

components/fctl/go.sum, components/ledger/internal/storage/ledgerstore/bucket.go, components/ledger/internal/storage/ledgerstore/migrations/9-fix-incorrect-volumes-aggregation.sql, components/ledger/internal/storage/ledgerstore/transactions_test.go, components/operator/docs/02-Installation.md, components/operator/helm/crds/Chart.yaml, components/operator/helm/operator/Chart.lock, components/operator/helm/operator/Chart.yaml, components/operator/helm/operator/values.yaml, docker-compose.yml, ee/agent/helm/Chart.yaml, ee/agent/helm/values.yaml, helm/regions/Chart.lock, helm/regions/Chart.yaml, helm/regions/values.yaml
- **fix(ledger): incorrect volumes (#1644)**
- **feat: prepare v2.0.11**
=> fix(ledger/backport): pr #1644"

components/payments/internal/api/v3/router.go, components/payments/internal/connectors/plugins/public/mangopay/client/webhooks.go, components/payments/internal/connectors/plugins/public/mangopay/plugin.go, components/payments/internal/connectors/plugins/public/mangopay/webhooks.go
=> fix(mangopay): fix webhooks handler

ee/gateway/openapi.yaml, releases/base.yaml, releases/sdks/go/.speakeasy/gen.lock, releases/sdks/go/README.md, releases/sdks/go/USAGE.md, releases/sdks/go/docs/pkg/models/shared/security.md, releases/sdks/go/docs/sdks/formance/README.md, releases/sdks/go/docs/sdks/formanceorchestrationv1/README.md, releases/sdks/go/docs/sdks/formancepaymentsv1/README.md, releases/sdks/go/docs/sdks/formancereconciliationv1/README.md, releases/sdks/go/docs/sdks/formancesearchv1/README.md, releases/sdks/go/docs/sdks/formancev1/README.md, releases/sdks/go/docs/sdks/formancev2/README.md, releases/sdks/go/docs/sdks/formancewalletsv1/README.md, releases/sdks/go/docs/sdks/formancewebhooksv1/README.md, releases/sdks/go/docs/sdks/v1/README.md, releases/sdks/go/docs/sdks/v2/README.md, releases/sdks/go/formance.go, releases/sdks/go/internal/hooks/clientcredentials.go, releases/sdks/go/pkg/models/shared/security.go
- update server URL to include organization and environment variables
- add NoAuthorization security scheme
- update security requirements for stack version info endpoint
=> feat: update API configuration and security schemes

components/ledger/internal/api/v2/utils.go, components/ledger/internal/storage/ledgerstore/accounts.go, ee/gateway/build.Dockerfile, ee/gateway/scratch.Dockerfile, tests/integration/suite/ledger-list-count-accounts.go, tests/integration/suite/ledger-list-transactions.go
- **feat: remove automatic pit on api**
- **feat: add first_usage filter on /accounts**
=> feat: add first_usage filter on /accounts

components/operator/docs/02-Installation.md, components/operator/helm/crds/Chart.yaml, components/operator/helm/operator/Chart.lock, components/operator/helm/operator/Chart.yaml, components/operator/helm/operator/values.yaml, docker-compose.yml, ee/agent/helm/Chart.yaml, ee/agent/helm/values.yaml, helm/regions/Chart.lock, helm/regions/Chart.yaml, helm/regions/values.yaml
=> chore: prepare v2.0.26
